stages:
  - build
  - deploy

build:
  stage: build
  script:
    - make build
  artifacts:
    name: "booster-jelix-org-${CI_COMMIT_SHA}"
    paths:
      - booster/var/config/
      - booster/vendor/
  only:
    - master
  tags:
    - jelix

deploy:
  stage: deploy
  script:
    - make deploy
  when: manual
  only:
    - master
  tags:
    - jelix
