stages:
  - build
  - deploy

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - booster/vendor/

build:
  stage: build
  script:
    - make build
  artifacts:
    name: "booster-jelix-org-${CI_COMMIT_SHA}"
    paths:
      - booster/var/config/
  only:
    - master
  tags:
    - jelix

deploy:
  stage: deploy
  script:
    - make deploy
  when: manual
  only:
    - master
  tags:
    - jelix
