#!/usr/bin/env bash

set -e

export JELIX_USER_ID=${JELIX_USER_ID:-$(id -u)}
export JELIX_GROUP_ID=${JELIX_GROUP_ID:-$(id -g)}

CMD=$1

export IMG_PREFIX=boosterjelix
export APPBRANCH=


if [ "$APP_WEB_PORT" == "" ]; then
  export APP_WEB_PORT=8227
fi

if [ "$PHP_VERSION" == "" ]; then
  export PHP_VERSION=7.4
fi

if [ ! -d ./jelix-design ]; then
  git clone https://github.com/jelix/jelix-design.git
fi

#if [ "$CMD" == "build" ]; then

#fi

if [ "$CMD" == "reset" ]; then
    # Stop/Remove containers
    docker-compose -p ${IMG_PREFIX}-tests${APPBRANCH} rm -sf || true
    # Clean db volumes
    docker volume rm "${IMG_PREFIX}_mysql_data${APPBRANCH}" || true
    exit 0
elif [ -z "$CMD" ]; then
    CMD="up"
else
    shift
fi


docker-compose -p ${IMG_PREFIX}-tests${APPBRANCH} $CMD
